# Generated by Django 4.1.6 on 2023-03-18 23:58

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_image_alter_productcategory_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd')], max_length=2)),
                ('phone', phone_field.models.PhoneField(max_length=31)),
                ('car_name', models.CharField(max_length=255)),
                ('reserve_for', models.DateTimeField()),
            ],
        ),
    ]
